# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Vivien/Documents/Master/S2/LPSC/Section11/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/blk_mem_bram/blk_mem_bram.xci
# IP: The module: 'blk_mem_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vivien/Documents/Master/S2/LPSC/Section11/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/blk_mem_bram/blk_mem_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Vivien/Documents/Master/S2/LPSC/Section11/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/blk_mem_bram/blk_mem_bram.xci
# IP: The module: 'blk_mem_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vivien/Documents/Master/S2/LPSC/Section11/mse_mandelbrot_no_bram/mse_mandelbrot.srcs/sources_1/ip/blk_mem_bram/blk_mem_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
